source <sfile>:p:h/function.vim

if has('win32')
	"maximizes Window.
	autocmd GUIEnter * simalt ~x

	language messages en
endif
if has('multi_byte_ime')
	highlight Cursor guifg=NONE guibg=Green
	highlight CursorIM guifg=NONE guibg=Purple
endif

source <sfile>:p:h/option.vim

syntax on

source <sfile>:p:h/keymap.vim

if filereadable(getcwd() . '/user.vimrc')
	source user.vimrc
endif

