hryky::task::distributor::Base Class Reference
attaches workers to the concurrent units.
#include <task_distributor_base.h>
Classes
struct ResetParameter
the set of parameters to reset
class WorkerObserver
callback functions from hryky::task::worker::Base
Public Types
typedef Base this_type
self
Public Member Functions
bool attach ()
attaches all workers to concurrent units.
Base ()
default constructor
bool error () const
confirms that some error occurred.
bool join ()
suspends the current thread until all workers are detached from concurrent units.
bool reset (ResetParameter const &param)
clears and recreates the resources
size_t workers_size () const
returns the number of workers
virtual ~Base ()
destructor
Protected Member Functions
bool implement (worker::Base &worker, size_t index)
assigns an implementation of worker.
workers_type::reference worker (size_t index)
returns a worker indicated by index.
workers_type::iterator workers_begin ()
returns the beginning of the array of workers.
workers_type::const_iterator workers_begin () const
returns the beginning of the array of workers (const).
workers_type::iterator workers_end ()
returns the end of the array of workers.
workers_type::const_iterator workers_end () const
returns the end of the array of workers (const).
Private Types
typedef Noncopyable * instance_type
instance type
Detailed Description
attaches workers to the concurrent units.
Parameters
WorkerT is derived class of task::worker::Base.
Attention
The instance of this class shall not be released during the lifetime of the passed concurrency module.
Constructor & Destructor Documentation
Base::Base () [explicit]
default constructor
default constructor.
Base::~Base () [virtual]
destructor
destructor.
References hryky::clear().
Member Function Documentation
bool Base::attach ()
attaches all workers to concurrent units.
Returns
success or failure.
If the workers are not attached to each concurrent unit, they are added to the waiting queue of the each concurrent unit synchronously.
Attention
This function includes the synchronization using exclusive control. (i.e. The calling context may be suspended for log periods.)
References hryky_log_err.
bool Base::implement (worker::Base & worker, size_t index) [protected]
assigns an implementation of worker.
assigns the implementation of worker.
bool Base::join ()
suspends the current thread until all workers are detached from concurrent units.
suspends until all workers are detached from concurrent units.
Returns
success or failure.
Attention
The caller context might be suspended for long periods.
There might be deadlock if exclusion controls are not used appropriately.
Derived instance MUST call this method before implementations of workers are destructed.
References hryky_log_err.
bool Base::reset (ResetParameter const & param)
clears and recreates the resources
clears and recreates the resources.
Reimplemented in hryky::task::distributor::Batch< TaskT >.
References hryky::clear(), hryky::memory::global::heap(), hryky_log_err, HRYKY_NULLPTR, hryky::reduction::map(), hryky::Vector< ValueT, AllocatorT >::resize(), and hryky::task::Concurrency::units_size().
The documentation for this class was generated from the following files:
task_distributor_base.h
task_distributor_base.cpp