hryky::task::distributor::Impl< WorkerT > Class Template Reference
base class of implementation for task::distributor::Base.
#include <task_distributor_impl.h>
Public Types
typedef Base base_type
base class of inheritance
typedef Impl< WorkerT > this_type
self
typedef WorkerT worker_type
type of worker
Public Member Functions
bool attach ()
attaches all workers to concurrent units.
bool error () const
confirms that some error occurred.
bool join ()
suspends the current thread until all workers are detached from concurrent units.
reduction_type reduce (reduction::name_type const &name) const
output the information of hryky::task::distributor::Impl.
bool reset (ResetParameter const &param)
clears and recreates the resources
size_t workers_size () const
returns the number of workers
Protected Member Functions
Impl ()
default constructor.
void implement (workers_type &workers)
assigns implementations of workers to the interfaces which the base class has.
bool implement (worker::Base &worker, size_t index)
assigns an implementation of worker.
worker_type & worker (size_t index)
retrieves the implementation of worker.
worker_type const & worker (size_t index) const
retrieves the implementation of worker (const).
workers_type::iterator workers_begin ()
retrieves the beginning of the range of workers.
workers_type::const_iterator workers_begin () const
retrieves the beginning of the range of workers (const).
workers_type::iterator workers_end ()
retrieves the end of the range of workers.
workers_type::const_iterator workers_end () const
retrieves the end of the range of workers (const).
virtual ~Impl ()
destructor.
Detailed Description
template<typename WorkerT>class hryky::task::distributor::Impl< WorkerT >
base class of implementation for task::distributor::Base.
Member Function Documentation
bool Base::attach () [inherited]
attaches all workers to concurrent units.
Returns
success or failure.
If the workers are not attached to each concurrent unit, they are added to the waiting queue of the each concurrent unit synchronously.
Attention
This function includes the synchronization using exclusive control. (i.e. The calling context may be suspended for log periods.)
References hryky_log_err.
bool Base::implement (worker::Base & worker, size_t index) [protected, inherited]
assigns an implementation of worker.
assigns the implementation of worker.
bool Base::join () [inherited]
suspends the current thread until all workers are detached from concurrent units.
suspends until all workers are detached from concurrent units.
Returns
success or failure.
Attention
The caller context might be suspended for long periods.
There might be deadlock if exclusion controls are not used appropriately.
Derived instance MUST call this method before implementations of workers are destructed.
References hryky_log_err.
bool Base::reset (ResetParameter const & param) [inherited]
clears and recreates the resources
clears and recreates the resources.
Reimplemented in hryky::task::distributor::Batch< TaskT >.
References hryky::clear(), hryky::memory::global::heap(), hryky_log_err, HRYKY_NULLPTR, hryky::reduction::map(), hryky::Vector< ValueT, AllocatorT >::resize(), and hryky::task::Concurrency::units_size().
The documentation for this class was generated from the following file:
task_distributor_impl.h