hryky::memory::heap::Arbitrary< OffsetT > Class Template Reference
'not' thread-safe memory allocation for usage in one thread.
#include <memory_heap_arbitrary.h>
Classes
struct Address
wrapper to print an address allocated from heap
Public Types
typedef OffsetT offset_type
self
Public Member Functions
size_t allocatable_size () const
retrieves the maximum size of allocate() can be successful.
size_t allocatable_size (alignment_type const alignment) const
retrieves the maximum size of allocate() can be successful.
virtual void * allocate (size_t const size)
allocates memory on default alignment.
void * allocate (size_t size, alignment_type alignment)
allocates memory.
Arbitrary ()
default constructor
size_t capacity () const
gets the initial available size in bytes.
virtual bool deallocate (void *const address)
deallocates memory.
offset_type free_nodes_size () const
gets the number of fragmented free nodes.
reduction_type reduce (reduction::name_type const &name) const
outputs the information of heap.
reduction_type reduce (reduction::name_type const &name, void const *address) const
outputs the information of the address allocated by hryky::memory::heap::Arbitrary.
bool reset (void *buffer, size_t buffer_size, alignment_type alignment)
clears previous buffer and reinitialize instance.
bool reset (void *buffer, size_t buffer_size)
clears previous buffer and reinitialize instance with default alignment
bool verify () const
checks validity
~Arbitrary ()
destrunctor
Detailed Description
template<typename OffsetT = size_t>class hryky::memory::heap::Arbitrary< OffsetT >
'not' thread-safe memory allocation for usage in one thread.
Attention
restrictions:
The total size of allocations depends on the address alignment passed to Arbitrary::reset(). The bit-width of capacity depends on the alignment(1) and the bit-width of offset_type(2). For example, if the (1) is `4` and (2) is `16`, the bit-width of capacity is `16 + 4 = 20`. Then, you can allocate memory amount to `0x10000(2^20) - system_size` bytes at most.
The total number of allocation unit depends on the OffsetT template argument. OffsetT represents position of each memory block internally. Therefore, if you select Arbitrary<uint8_t> class, you can allocate (256 - system usage) blocks at most.
The all of member functions are `not` thread-safe.
Member Typedef Documentation
template<typename OffsetT = size_t> typedef OffsetT hryky::memory::heap::Arbitrary< OffsetT >::offset_type
self
You can handle memory blocks up to the maximum number of offset_type.
Constructor & Destructor Documentation
template<typename OffsetT > hryky::memory::heap::Arbitrary< OffsetT >::Arbitrary () [explicit]
default constructor
constructor.
template<typename OffsetT > hryky::memory::heap::Arbitrary< OffsetT >::~Arbitrary ()
destrunctor
destrunctor.
Member Function Documentation
template<typename OffsetT = size_t> size_t hryky::memory::heap::Arbitrary< OffsetT >::allocatable_size () const [inline]
retrieves the maximum size of allocate() can be successful.
Returns
the maximim size of allocate() can be successful.
address alignment is based on the alignment past at Arbitrary::reset().
template<typename OffsetT > size_t hryky::memory::heap::Arbitrary< OffsetT >::allocatable_size (alignment_type const alignment) const
retrieves the maximum size of allocate() can be successful.
retrieves the maximum size of allocation can be successful.
Parameters
alignment is the unit of each allocation
Returns
the maximim size of allocate() can be successful.
References hryky::align_ceil(), hryky_log_emerg, and hryky::reduction::map().
template<typename OffsetT = size_t> virtual void* hryky::memory::heap::Arbitrary< OffsetT >::allocate (size_t const size) [inline, virtual]
allocates memory on default alignment.
Parameters
size is the size of allocated memory
Note
the address alignment of the returned address is based on the alignment past at Arbitrary::reset().
template<typename OffsetT > void * hryky::memory::heap::Arbitrary< OffsetT >::allocate (size_t size, alignment_type alignment)
allocates memory.
allocates memory on specified alignment.
Parameters
size is the size of allocated memory.
alignment is the address alingment of returned address.
Return values
HRYKY_NULLPTR failure
!HRYKY_NULLPTR an allocated address
Note
First-fit is adopted.
If a found free block has enough room after allocated area, a new free block is created just behind allocated area. Then the new free block can be searched first at next allocation.
...| prev block | found block | next block |... => ...| prev block | allocated block | free block | next block |...
If the gap of alignment between a found free block and required alignment has enough room, a new free block is created just before allocated area. Then the new free block can be searched first at next allocation.
...| prev block | found block | next block |... => ...| prev block | free block | allocated block | next block |...
If both of new free blocks described above are created, the forward one is searched first at next allocation.
...| prev block | found block | next block |... => ...| prev block | forward free block | allocated block | backward free block | next block |...
References hryky::align_ceil(), hryky_log_emerg, hryky_log_err, HRYKY_NULLPTR, and hryky::reduction::map().
template<typename OffsetT > bool hryky::memory::heap::Arbitrary< OffsetT >::deallocate (void *const address) [virtual]
deallocates memory.
Parameters
address is the deallocated address.
Returns
success and failure.
Note
If the block before deallocated block is free block, the forward block and deallocated block are concatenated.
...| free block(A) | deallocated block(B) | used block |... => ...| free block(A+B) | used block |...
If the block after deallocated block is free block, the backward block and deallocated block are concatenated.
...| used block | deallocated block(A) | free block(B) |... => ...| used block | free block(A+B) |...
References hryky_log_emerg, hryky_log_err, and hryky::reduction::map().
template<typename OffsetT > bool hryky::memory::heap::Arbitrary< OffsetT >::reset (void * buffer, size_t buffer_size, alignment_type alignment)
clears previous buffer and reinitialize instance.
Parameters
buffer is buffer in which the heap is created
buffer_size is the size of buffer
alignment is the unit of each allocation
Returns
success and failure.
Attention
The maximum size of available buffer depends on offset_type and alignment.
References hryky::align_ceil(), hryky::align_floor(), hryky_log_emerg, hryky_log_warning, and hryky::reduction::map().
Referenced by hryky::memory::heap::Arbitrary< OffsetT >::reset().
template<typename OffsetT = size_t> bool hryky::memory::heap::Arbitrary< OffsetT >::reset (void * buffer, size_t buffer_size) [inline]
clears previous buffer and reinitialize instance with default alignment
Parameters
buffer is buffer in which the heap is created
buffer_size is the size of buffer
Returns
success and failure
References hryky::memory::heap::Arbitrary< OffsetT >::reset().
template<typename OffsetT > bool hryky::memory::heap::Arbitrary< OffsetT >::verify () const
checks validity
checks validity.
References hryky_log_crit, and hryky::reduction::map().
The documentation for this class was generated from the following files:
memory_heap_arbitrary.h
memory_heap_arbitrary.cpp