hryky::exclusion::Atomic< ValueT, LockableT > Class Template Reference
synchronizes a access to an object.
#include <exclusion_atomic.h>
Public Types
typedef Atomic< ValueT, LockableT > this_type
self
Public Member Functions
Atomic ()
default constructor.
Atomic (typename CallTraits< value_type >::param_type value)
constructor with the initial value.
Atomic (this_type const &rhs)
copy constructor.
value_type compare_and_swap (typename CallTraits< value_type >::param_type old_value, typename CallTraits< value_type >::param_type new_value)
assigns a new value if the internal value is same with a given value.
template<typename FunctorT >
ValueT exclude (FunctorT &functor)
executes an arbitrary functor under the exclusive control.
operator value_type () const
reads the value.
operator ValueT () const
casts to the type of the value.
this_type & operator%= (typename CallTraits< ValueT >::param_type rhs)
assigns the remainder divided by the value to this instance.
this_type & operator*= (typename CallTraits< ValueT >::param_type rhs)
multiplies the value to the this instance.
this_type & operator++ ()
pre-increments the value.
value_type operator++ (int)
post-increments the value.
this_type & operator+= (typename CallTraits< ValueT >::param_type rhs)
appends the value to the this instance.
this_type & operator-- ()
pre-decrements the value.
value_type operator-- (int)
post-decrements the value.
this_type & operator-= (typename CallTraits< ValueT >::param_type rhs)
subtracts the value from the this instance.
this_type & operator/= (typename CallTraits< ValueT >::param_type rhs)
divides the this instance by the value.
this_type & operator= (this_type const &rhs)
assigns a new instance.
this_type & operator= (typename CallTraits< value_type >::param_type rhs)
assigns a new value.
Detailed Description
template<typename ValueT, typename LockableT = exclusion::Mutex>class hryky::exclusion::Atomic< ValueT, LockableT >
synchronizes a access to an object.
Since
2011-11-29T15:13:33+0900
Parameters
ValueT is the type of the object accessed through this class.
Constructor & Destructor Documentation
template<typename ValueT , typename LockableT = exclusion::Mutex> hryky::exclusion::Atomic< ValueT, LockableT >::Atomic (typename CallTraits< value_type >::param_type value) [inline]
constructor with the initial value.
Parameters
value is the left-hand side of the assignment.
template<typename ValueT , typename LockableT = exclusion::Mutex> hryky::exclusion::Atomic< ValueT, LockableT >::Atomic (this_type const & rhs) [inline]
copy constructor.
Parameters
rhs is the left-hand side of the assignment.
The elements in the value of right-hand side are consistent.
Member Function Documentation
template<typename ValueT , typename LockableT = exclusion::Mutex> hryky::exclusion::Atomic< ValueT, LockableT >::operator value_type () const [inline]
reads the value.
Returns
the copied value.
References hryky::log::format::value().
template<typename ValueT , typename LockableT = exclusion::Mutex> this_type& hryky::exclusion::Atomic< ValueT, LockableT >::operator= (this_type const & rhs) [inline]
assigns a new instance.
Parameters
rhs is the left-hand side of the assignment.
Returns
the reference of this instance.
The elements in the value of right-hand side are consistent.
Reimplemented from hryky::exclusion::AtomicWriting< ValueT, LockableT >.
References hryky::exclusion::AtomicWriting< ValueT, LockableT >::operator=().
template<typename ValueT , typename LockableT = exclusion::Mutex> this_type& hryky::exclusion::Atomic< ValueT, LockableT >::operator= (typename CallTraits< value_type >::param_type rhs) [inline]
assigns a new value.
Parameters
rhs is the left-hand side of the assignment.
Returns
the reference of this instance.
Reimplemented from hryky::exclusion::AtomicWriting< ValueT, LockableT >.
References hryky::exclusion::AtomicWriting< ValueT, LockableT >::operator=().
The documentation for this class was generated from the following file:
exclusion_atomic.h