hryky::Vector< ValueT, AllocatorT > Class Template Reference
substitutes for std::vector container.
#include <vector.h>
Public Member Functions
template<typename InputIterator >
bool assign (InputIterator begin, InputIterator end)
assigns the multiple elements between [begin,end).
bool assign (size_type size, const_reference value)
assigns the copies of an element.
reference at (size_type index)
retrieves the mutable element with offset.
const_reference at (size_type index) const
retrieves the immutable element with offset.
reference back ()
retrieves the mutable last element.
const_reference back () const
retrieves the immutable last element.
iterator begin ()
retrieves a forward iterator referring to the first mutable element.
const_iterator begin () const
retrieves a forward iterator referring to the first immutable element.
size_type capacity () const
bool clear ()
makes the container empty.
bool empty () const
confirms whether container has no element.
iterator end ()
retrieves a forward iterator referring to the last mutable element.
const_iterator end () const
retrieves a forward iterator referring to the last immutable element.
iterator erase (iterator first, iterator last)
removes some elements between two iterators.
reference first ()
retrieves the mutable first element.
const_reference first () const
retrieves the immutable first element.
allocator_type get_allocator () const
retrieves the allocator of this instance.
iterator insert (iterator position, const_reference value)
inserts an element before the element at the indicated iterator.
template<typename InputIteratorT >
bool insert (iterator position, InputIteratorT first, InputIteratorT last)
inserts the elements between two input iterator.
size_type max_size () const
retrieves the maximum number of allocatable elements.
reference operator[] (size_type index)
retrieves the mutable element with offset.
const_reference operator[] (size_type index) const
retrieves the immutable element with offset.
bool pop_back ()
removes the last element.
bool push_back (const_reference src)
adds the element into the end of container.
reverse_iterator rbegin ()
retrieves a backward iterator referring to the first mutable element.
const_reverse_iterator rbegin () const
retrieves a backward iterator referring to the first immutable element.
reverse_iterator rend ()
retrieves a backward iterator referring to the last mutable element.
const_reverse_iterator rend () const
retrieves a backward iterator referring to the last immutable element.
bool reserve (size_type const capacity)
allocates memory
bool resize (size_type const size)
expands or shrinks the length of the container.
size_type size () const
retrieves the number of elements.
void swap (this_type &src)
interchanges all internal values.
Vector ()
default constructor.
Vector (this_type const &rhs)
copy constructor.
Vector (this_type &&rhs)
copy constructor by rvalue reference.
Vector (allocator_type const &allocator)
constructor with allocator.
~Vector ()
destructor.
Public Attributes
hryky_assign_op
assignment operator.
Detailed Description
template<typename ValueT, typename AllocatorT = hryky::allocator::Heap<ValueT>>class hryky::Vector< ValueT, AllocatorT >
substitutes for std::vector container.
Member Function Documentation
template<typename ValueT , typename AllocatorT > hryky::Vector< ValueT, AllocatorT >::size_type hryky::Vector< ValueT, AllocatorT >::capacity () const
retrieves the number of elements that is able to be held without additional memory allocation
Referenced by hryky::reduce().
template<typename ValueT , typename AllocatorT > bool hryky::Vector< ValueT, AllocatorT >::reserve (size_type const capacity)
allocates memory
Returns
success and failure
References HRYKY_NULLPTR.
Referenced by hryky::display::Screen::reset(), hryky::task::worker::Batch< TaskT >::reset(), and hryky::Vector< ValueT, AllocatorT >::Vector().
The documentation for this class was generated from the following file:
vector.h