hryky::task::Concurrency Class Reference
manages concurrency units.
#include <task_concurrency.h>
Classes
struct ResetParameter
the parameters of reset()
Public Types
typedef Concurrency this_type
self
Public Member Functions
Concurrency ()
default constructor
void inactivate (Sequence &sequence)
inactivates the working sequence.
bool join (duration_type const &duration)
waits until the all sequences end.
reduction_type reduce (reduction::name_type const &name) const
outputs the information formatted as string.
bool reset (ResetParameter const &param)
clears existing resources and recreate new resources
Sequence & sequence (size_t index)
returns a sequence
size_t units_size () const
returns the number of concurrent units
~Concurrency ()
destructor
Private Types
typedef Noncopyable * instance_type
instance type
Detailed Description
manages concurrency units.
Constructor & Destructor Documentation
hryky::task::Concurrency::Concurrency () [explicit]
default constructor
constructor.
hryky::task::Concurrency::~Concurrency ()
destructor
destrunctor.
References hryky::clear().
Member Function Documentation
bool hryky::task::Concurrency::join (duration_type const & duration)
waits until the all sequences end.
waits until the all sequences end..
bool hryky::task::Concurrency::reset (ResetParameter const & param)
clears existing resources and recreate new resources
clears existing resources and recreate new resources.
References hryky::Foreach< ContainerT, IteratorT >::begin(), hryky::clear(), hryky::thread::hardware_concurrency(), hryky::memory::global::heap(), hryky_log_err, hryky_log_notice, HRYKY_NULLPTR, hryky::reduction::map(), and hryky::Vector< ValueT, AllocatorT >::resize().
hryky::task::Sequence & hryky::task::Concurrency::sequence (size_t index)
returns a sequence
returns a sequence.
Referenced by hryky::task::distributor::Batch< TaskT >::reset().
size_t hryky::task::Concurrency::units_size () const
returns the number of concurrent units
returns the number of concurrent units.
Referenced by hryky::task::distributor::Batch< TaskT >::reset(), and hryky::task::distributor::Base::reset().
The documentation for this class was generated from the following files:
task_concurrency.h
task_concurrency.cpp