hryky::String< CharT, AllocatorT > Class Template Reference
substitutes for std::string.
#include <string.h>
Public Member Functions
this_type & append (this_type const &src)
appends the additional string at the end of this instance.
this_type & append (this_type const &str, size_type offset, size_type size)
appends the substring of the other string at the end of this instance.
this_type & append (const_pointer str, size_type str_size)
appends an array of characters with the lengh of the array.
template<typename InputIterator >
this_type & append (InputIterator first, InputIterator last)
appends the elements between two iterators.
this_type & assign (this_type const &str)
assigns the content from the other string.
this_type & assign (this_type const &str, size_type pos, size_type size)
assigns the substring of the other string.
this_type & assign (const_pointer str, size_type size)
assigns an array of characters.
template<typename InputIterator >
this_type & assign (InputIterator first, InputIterator last)
assigns elements between two iterators.
const_reference at (size_type const index) const
retrieves the immutable element specified by index.
reference at (size_type const index)
retrieves the mutable element specified by index.
iterator begin ()
retrieves a forward iterator referring to the first mutable element.
const_iterator begin () const
retrieves a forward iterator referring to the first immutable element.
const_pointer c_str () const
retrieves null-terminated characters.
size_type capacity () const
void clear ()
removes the all elements in this string.
const_pointer data () const
retrieves the internal array of characters.
bool empty () const
confirms whether container has no element.
iterator end ()
retrieves a forward iterator referring to the last mutable element.
const_iterator end () const
retrieves a forward iterator referring to the last immutable element.
iterator erase (iterator itr)
removes one character at the position specified by iterator.
iterator erase (iterator first, iterator last)
removes characters between two iterators.
allocator_type get_allocator () const
retrieves the allocator of this instance.
this_type & insert (size_type pos, this_type const &str)
inserts the other string.
this_type & insert (size_type dest_pos, this_type const &str, size_type src_pos, size_type src_size)
inserts the part of the other string.
this_type & insert (size_type pos, const_pointer str, size_type size)
inserts an array of characters.
template<typename InputIterator >
this_type & insert (iterator dest_itr, InputIterator first, InputIterator last)
inserts the elements between two iterators.
this_type & insert (iterator itr, value_type const value)
inserts a character.
size_type length () const
retrieves the length of this string.
size_type max_size () const
retrieves the maximum number of allocatable elements.
bool operator!= (this_type const &rhs) const
confirms whether each string has different value.
bool operator!= (CharT const *const rhs) const
this_type & operator+= (this_type const &rhs)
appends the elements of other string at the end of this string.
this_type & operator+= (value_type const rhs)
appends a character.
bool operator< (this_type const &rhs) const
bool operator< (CharT const *const rhs) const
bool operator<= (this_type const &rhs) const
bool operator<= (CharT const *const rhs) const
confirms whether this string is less than or equal to the null-terminated characters in dictionary order.
this_type & operator= (const_pointer const rhs)
assigns a new string by null-terminated characters.
template<size_t Size>
this_type & operator= (value_type const (&rhs)[Size])
assigns a new string by array of characters.
bool operator== (this_type const &rhs) const
confirms whether both strings have same characters.
bool operator== (CharT const *const rhs) const
bool operator> (this_type const &rhs) const
bool operator> (CharT const *const rhs) const
confirms whether this string is greater than the null- terminated characters in dictionary order.
bool operator>= (this_type const &rhs) const
bool operator>= (CharT const *const rhs) const
const_reference operator[] (size_type const index) const
retrieves the immutable element specified by index.
reference operator[] (size_type const index)
retrieves the mutable element specified by index.
bool push_back (value_type const value)
appends a character at the end of this instance.
reverse_iterator rbegin ()
retrieves a backward iterator referring to the first mutable element.
const_reverse_iterator rbegin () const
retrieves a backward iterator referring to the first immutable element.
reduction_type reduce (reduction::name_type const &name) const
outputs the information formatted as string.
reverse_iterator rend ()
retrieves a backward iterator referring to the last mutable element.
const_reverse_iterator rend () const
retrieves a backward iterator referring to the last immutable element.
this_type & replace (size_type dest_pos, size_type dest_size, this_type const &src)
replaces the part of the this instance by other string.
this_type & replace (iterator dest_first, iterator dest_last, this_type const &src)
replaces the range between two iterators of this instance by other string.
this_type & replace (size_type dest_pos, size_type dest_size, this_type const &src, size_type src_pos, size_type src_size)
replaces the part of the this instance by the substring of other instance.
this_type & replace (size_type dest_pos, size_type dest_size, const_pointer src, size_type src_size)
replaces the part of the this instance by the part of the array of characters.
this_type & replace (iterator dest_first, iterator dest_last, const_pointer src, size_type src_size)
replaces the range between two iterators of this instance by the part of the array of characters.
template<typename InputIterator >
this_type & replace (iterator dest_first, iterator dest_last, InputIterator src_first, InputIterator src_last)
replaces the range between two iterators of this instance by the range of the other instance.
bool reserve (size_type const capacity)
expands the available region to allocate additional characters.
bool resize (size_type const size)
expands or shrinks the length of string.
size_type size () const
retrieves the number of elements.
String ()
default constructor.
String (this_type const &rhs)
copy constructor.
String (this_type &&rhs)
copy constructor by rvalue reference.
String (allocator_type const &allocator)
constructor with allocator.
String (const_pointer str, size_type str_size, allocator_type allocator=allocator_type())
constructor with character array.
String (const_pointer str, allocator_type allocator=allocator_type())
constructor with null terminated characters.
void swap (this_type &src)
exhanges all internal values.
template<typename StreamT >
StreamT & write_to (StreamT &stream) const
outputs the information of reduction::Base.
~String ()
destructor.
Static Public Member Functions
static value_type terminator ()
terminator.
Public Attributes
hryky_assign_op
assignment operator.
Static Public Attributes
static size_type const npos = static_cast<size_type>(-1)
the index which specifies the end of string.
Detailed Description
template<typename CharT = char, typename AllocatorT = hryky::allocator::Heap<CharT>>class hryky::String< CharT, AllocatorT >
substitutes for std::string.
Attention
This class is under construction.
Constructor & Destructor Documentation
template<typename CharT , typename AllocatorT > hryky::String< CharT, AllocatorT >::String (const_pointer str, size_type str_size, allocator_type allocator = allocator_type())
constructor with character array.
constructor with an array of characters.
References hryky::String< CharT, AllocatorT >::reserve(), and hryky::String< CharT, AllocatorT >::terminator().
Member Function Documentation
template<typename CharT , typename AllocatorT > hryky::String< CharT, AllocatorT >::size_type hryky::String< CharT, AllocatorT >::capacity () const
retrieves the number of elements that is able to be held without additional memory allocation
template<typename CharT , typename AllocatorT > bool hryky::String< CharT, AllocatorT >::operator!= (CharT const *const rhs) const
confirms whether this string has different characters from the null-terminated characters.
template<typename CharT , typename AllocatorT > bool hryky::String< CharT, AllocatorT >::operator< (this_type const & rhs) const
confirms whether this string is less than the other string in dictionary order.
References hryky::String< CharT, AllocatorT >::size().
template<typename CharT , typename AllocatorT > bool hryky::String< CharT, AllocatorT >::operator< (CharT const *const rhs) const
confirms whether this string is less than the null-terminated characters in dictionary order.
template<typename CharT , typename AllocatorT > bool hryky::String< CharT, AllocatorT >::operator<= (this_type const & rhs) const
confirms whether this string is less than or equal to the other string in dictionary order.
References hryky::String< CharT, AllocatorT >::size().
template<typename CharT , typename AllocatorT > bool hryky::String< CharT, AllocatorT >::operator<= (CharT const *const rhs) const
confirms whether this string is less than or equal to the null-terminated characters in dictionary order.
confirms whether this string is less than or equal to the null- terminated characters in dictionary order.
template<typename CharT , typename AllocatorT > bool hryky::String< CharT, AllocatorT >::operator== (CharT const *const rhs) const
confirms whether this string has same characters as the null-terminated characters.
template<typename CharT , typename AllocatorT > bool hryky::String< CharT, AllocatorT >::operator> (this_type const & rhs) const
confirms whether this string is greater than the other string in dictionary order.
template<typename CharT , typename AllocatorT > bool hryky::String< CharT, AllocatorT >::operator> (CharT const *const rhs) const
confirms whether this string is greater than the null- terminated characters in dictionary order.
confirms whether this string is greater than the null-terminated characters in dictionary order.
template<typename CharT , typename AllocatorT > bool hryky::String< CharT, AllocatorT >::operator>= (this_type const & rhs) const
confirms whether this string is greater than or equal to the other string in dictionary order.
template<typename CharT , typename AllocatorT > bool hryky::String< CharT, AllocatorT >::operator>= (CharT const *const rhs) const
confirms whether this string is greater than or equal to the null-terminated characters in dictionary order.
The documentation for this class was generated from the following file:
string.h