hryky::memory::heap::Fixed Class Reference
memory allocation for fixed length units.
#include <memory_heap_fixed.h>
Classes
struct Address
the information of a address allocated from hryky::memory::heap::Fixed.
Public Types
enum { min_alignment_ = 3,
min_unit_size_ = (1 << min_alignment_)
 }
typedef uint64_t index_type
index of units array
typedef Fixed this_type
self
Public Member Functions
void * allocate ()
finds a free unit.
index_type allocated_size () const
gets the number of allocated units.
index_type available_size () const
gets the number of available units.
index_type capacity () const
gets the number of all units.
bool deallocate (void *src)
marks a unit as unused.
Fixed ()
default constructor
reduction_type reduce (reduction::name_type const &name) const
outputs the information of this instance.
reduction_type reduce (reduction::name_type const &name, void const *address) const
outputs the information of an address allocated from hryky::memory::heap::Fixed.
bool reset (void *buffer, size_t buffer_size, size_t unit_size)
sets up initial buffer.
bool verify () const
checks the validity of the internal data.
bool verify (void const *src) const
verifies allocated address.
~Fixed ()
destrunctor
Static Public Member Functions
static size_t buffer_size (size_t unit_size, index_type num)
estimates the required size of buffer.
Detailed Description
memory allocation for fixed length units.
Examples:
test_memory_heap_fixed.cpp.
Member Enumeration Documentation
anonymous enum
Enumerator:
min_alignment_
 minimum address alignment in bits
min_unit_size_
 minimum size of one unit in bytes
Constructor & Destructor Documentation
hryky::memory::heap::Fixed::Fixed () [explicit]
default constructor
constructor.
hryky::memory::heap::Fixed::~Fixed ()
destrunctor
destrunctor.
Member Function Documentation
void * hryky::memory::heap::Fixed::allocate ()
finds a free unit.
Return values
HRYKY_NULLPTR failure
!HRYKY_NULLPTR The address to an allocated unit.
The returned address is fixed length. The length is unit_size which you passed to reset().
References HRYKY_NULLPTR.
size_t hryky::memory::heap::Fixed::buffer_size (size_t unit_size, index_type num) [static]
estimates the required size of buffer.
Parameters
unit_size The size of one allocation unit in bytes
num The number of the units
Returns
The enough size to allocate units in bytes
When you pass the returned value of this function to Fixed::reset() as buffer_size, you should pass an address which is aligned on at least (1 << Fixed::min_alignment_) bytes. If not, the size of units that you can allocate is less than num.
bool hryky::memory::heap::Fixed::deallocate (void * src)
marks a unit as unused.
Parameters
src The address allocated by this instance
Returns
success and failure
References hryky_log_err, and hryky::reduction::map().
hryky::reduction_type hryky::memory::heap::Fixed::reduce (reduction::name_type const & name) const
outputs the information of this instance.
Parameters
name is the key of key-value pair.
Returns
an element of logging format.
References hryky::reduction::map().
Referenced by hryky::memory::heap::reduce().
hryky::reduction_type hryky::memory::heap::Fixed::reduce (reduction::name_type const & name, void const * address) const
outputs the information of an address allocated from hryky::memory::heap::Fixed.
Parameters
name is the key of key-value pair.
address will be the address allocated by this instance.
Returns
an element of logging format.
References hryky::reduction::map().
bool hryky::memory::heap::Fixed::reset (void * buffer, size_t buffer_size, size_t unit_size)
sets up initial buffer.
sets up an initial buffer.
Parameters
buffer An address on which allocation units are placed
buffer_size the size of buffer
unit_size The size of one allocation unit in bytes
Returns
success and failure
Attention
If you want to use entire region of buffer, you must adhere to the following items.
buffer must be alinged on (1 << Fixed::min_alignment_) bytes.
unit_size must be in multiple of Fixed::min_unit_size_.
References hryky::align_ceil(), hryky_log_err, hryky::reduction::map(), and min_alignment_.
bool hryky::memory::heap::Fixed::verify () const
checks the validity of the internal data.
Returns
valid and invalid
This function checks whether the internal information is corrupted.
References hryky_log_err, and hryky::reduction::map().
bool hryky::memory::heap::Fixed::verify (void const * src) const
verifies allocated address.
Parameters
src an address allocated from this instance
This function confirms that the passed address is under the management of this instance.
The documentation for this class was generated from the following files:
memory_heap_fixed.h
memory_heap_fixed.cpp