hryky::reduction::Map Class Reference
aggregates the multiple named values with each name.
#include <reduction_map.h>
Public Types
typedef reduction::Base base_type
base class of inheritance.
typedef std::vector
*
< reduction_type > children_type
type of children
typedef Map this_type
self.
Public Member Functions
Map & append (Map &map)
appends the instance of reduction::Map as child.
Map & append (reduction_type const &src)
appends an instance of reduction::Base as a child.
template<typename ValueT >
Map & append (name_type const &name, ValueT const &value)
appends a key-value pair.
template<typename ValueT , size_t Size>
Map & append (char const (&name)[Size], ValueT const &value)
appends a key-value pair.
children_type const & children () const
retrieves the key-value fields.
void clear ()
releases the internal resources.
bool dispatch (Dispatcher &dispatcher) const
traverses the decomposed structure.
Map ()
default constructor.
Map (this_type const &rhs)
copy constructor.
Map (this_type &&rhs)
copy constructor by rvalue reference.
Map (name_type const &name)
constructor with name.
name_type const & name () const
retrieves the name.
void swap (this_type &src)
interchanges the each internal resources of two instances.
template<typename StreamT >
StreamT & write_to (StreamT &stream) const
outputs the information of reduction::Base.
~Map ()
destructor.
Public Attributes
hryky_assign_op
assignment operator.
Protected Member Functions
virtual void delete_self ()
deletes the self instance.
Friends
map_type map (name_type const &name)
creates an instance of reduction::Map.
Detailed Description
aggregates the multiple named values with each name.
Constructor & Destructor Documentation
hryky::reduction::Map::Map (name_type const & name) [explicit]
constructor with name.
Parameters
name is the key of a mapped pair.
Member Function Documentation
hryky::reduction::Map & hryky::reduction::Map::append (Map & map)
appends the instance of reduction::Map as child.
appends a instance of reduction::Map as child.
Parameters
map is the instance of reduction::Map
Returns
the self instance.
hryky::reduction::Map & hryky::reduction::Map::append (reduction_type const & src)
appends an instance of reduction::Base as a child.
appends a instance of reduction::Base as a child.
Parameters
src is the instance of reduction::Base
Returns
the self instance.
References hryky::IntrusivePtr< ValueT >::get().
template<typename ValueT > hryky::reduction::Map & hryky::reduction::Map::append (name_type const & name, ValueT const & value)
appends a key-value pair.
Parameters
name is the name of the child.
value is the value of the child.
Returns
the self instance.
References hryky_reduce().
template<typename ValueT , size_t Size> hryky::reduction::Map & hryky::reduction::Map::append (char const (&) name[Size], ValueT const & value)
appends a key-value pair.
Parameters
name is the name of the child.
value is the value of the child.
Returns
the self instance.
References hryky_reduce().
void Base::delete_self () [protected, virtual, inherited]
deletes the self instance.
delete the self instance.
Attention
This base implementation uses global `delete` operator.
If derived class is instantiated by operation other than global `new` operator, the derived class has to override this function.
bool Base::dispatch (Dispatcher & dispatcher) const [inherited]
traverses the decomposed structure.
traverses the decomposed structure with indents.
Referenced by hryky::reduction::Base::write_to().
Friends And Related Function Documentation
map_type map (name_type const & name) [friend]
creates an instance of reduction::Map.
Parameters
name is the name of the instance.
Returns
the instance.
The documentation for this class was generated from the following files:
reduction_map.h
reduction_map.cpp