hryky::http::header::cache::directive::dispatcher::Apply Class Reference
applies the implementation of cache-directive to cache-control.
#include <http_header_cache_directive_dispatcher_apply.h>
Public Types
typedef
*
hryky::http::header::cache::directive::dispatcher::Base base_type
base class of inheritance.
typedef Apply this_type
self.
Public Member Functions
Apply ()
default constructor.
Apply (this_type const &)
copy constructor.
Apply (this_type &&rhs)
copy constructor by rvalue reference.
Apply (control_type &control)
constructor.
void clear ()
releases the internal resources.
virtual bool operator() (specifier_type &specifier)
applies http::header::cache::specifier_type to cache-control.
virtual bool operator() (seconds_type &second)
applies http::header::cache::directive::seconds_type to cache-control.
virtual bool operator() (field_type &field)
applies http::header::cache::directive::field_type to cache_control.
reduction_type reduce (reduction::name_type const &name) const
decomposes the instance to primitive objects.
void swap (this_type &src)
interchanges the each internal resources of two instances.
virtual ~Apply ()
destructor.
Public Attributes
hryky_assign_op
assignment operator.
Protected Member Functions
void swap (this_type &src)
interchanges the each internal resources of two instances.
Detailed Description
applies the implementation of cache-directive to cache-control.
Member Function Documentation
bool hryky::http::header::cache::directive::dispatcher::Apply::operator() (field_type & field) [virtual]
applies http::header::cache::directive::field_type to cache_control.
applies http::header::cache::directive::field_type to control.
Reimplemented from hryky::http::header::cache::directive::dispatcher::Base.
References hryky::http::header::cache::directive::Field::begin(), hryky::http::header::cache::directive::Field::end(), and hryky::http::header::cache::directive::Field::kind().
The documentation for this class was generated from the following files:
http_header_cache_directive_dispatcher_apply.h
http_header_cache_directive_dispatcher_apply.cpp