hryky::task::worker::Base Class Reference
executes tasks.
#include <task_worker_base.h>
Classes
class Detach
allows to call detach() from the concurrent unit.
class Observer
callback functions.
struct ResetParameter
parameter for reset()
class Run
allows to call run() from the concurrent unit.
Public Types
typedef Base this_type
self
Public Member Functions
bool attach ()
attaches itself to the corresponding thread.
Base ()
default constructor
void error ()
notifies that some error occurs.
bool reset (ResetParameter const &param)
clears the existing resources and reinitializes.
virtual ~Base ()
destrunctor
Private Types
typedef Noncopyable * instance_type
instance type
Detailed Description
executes tasks.
derived class must implement run_impl().
Constructor & Destructor Documentation
Base::Base () [explicit]
default constructor
constructor.
Base::~Base () [virtual]
destrunctor
destrunctor.
Member Function Documentation
bool Base::attach ()
attaches itself to the corresponding thread.
Returns
success or failure.
This function becomes effective immediately.
Attention
you must not call this function again while the worker is attached to the concurrent unit.
References hryky_log_err, hryky_log_warning, HRYKY_NULLPTR, and hryky_reduce().
Referenced by hryky::task::distributor::Batch< TaskT >::attach_with().
bool Base::reset (ResetParameter const & param)
clears the existing resources and reinitializes.
Parameters
param is the set of parameters to reset.
Returns
failure and success.
Reimplemented in hryky::task::worker::Batch< TaskT >.
Referenced by hryky::task::distributor::Batch< TaskT >::reset().
The documentation for this class was generated from the following files:
task_worker_base.h
task_worker_base.cpp