Concurrent Task
Namespaces
namespace hryky
the root of all namespaces in hryky-codebase.
Classes
class hryky::task::Concurrency
manages concurrency units.
class hryky::task::distributor::Base
attaches workers to the concurrent units.
class hryky::task::distributor::Batch< TaskT >
manages workers which executes multiple tasks.
class hryky::task::distributor::Impl< WorkerT >
base class of implementation for task::distributor::Base.
class hryky::task::worker::Quicksort< TaskT >
executes quick-sort concurrently.
Functions
bool hryky::task::worker::Batch< TaskT >::append (task_const_reference task)
appends a task.
template<typename InputIterator >
bool hryky::task::worker::Batch< TaskT >::append (InputIterator begin, InputIterator end)
appends multiple tasks.
bool hryky::task::distributor::Batch< TaskT >::attach_with (task_const_reference task)
appends and executes a task.
hryky::task::worker::Batch< TaskT >::Batch ()
default constructor
hryky::task::distributor::Batch< TaskT >::Batch ()
default constructor
bool hryky::task::distributor::Batch< TaskT >::distribute (task_const_reference task)
passes a task to a worker.
template<typename InputIterator >
bool hryky::task::distributor::Batch< TaskT >::distribute (InputIterator begin, InputIterator end)
passes multiple tasks to workers.
hryky::task::distributor::Impl< WorkerT >::Impl ()
default constructor.
void hryky::task::distributor::Impl< WorkerT >::implement (workers_type &workers)
assigns implementations of workers to the interfaces which the base class has.
reduction_type hryky::task::distributor::Impl< WorkerT >::reduce (reduction::name_type const &name) const
output the information of hryky::task::distributor::Impl.
template<typename WorkerT >
reduction_type hryky::task::distributor::reduce (reduction::name_type const &name, Impl< WorkerT > const &impl)
outputs the information of hryky::task::distributor::Impl.
template<typename TaskT >
reduction_type hryky::task::distributor::reduce (reduction::name_type const &name, Batch< TaskT > const &batch)
outputs the information of hryky::task::distributor::Batch.
template<typename TaskT >
reduction_type hryky::task::worker::reduce (reduction::name_type const &name, Batch< TaskT > const &batch)
outputs the information of hryky::task::worker::Batch.
bool hryky::task::distributor::Batch< TaskT >::reset (ResetParameter const &param)
clears and recreates the resources.
bool hryky::task::worker::Batch< TaskT >::reset (ResetParameter const &param)
clears and recreates resources.
virtual void hryky::task::worker::Batch< TaskT >::run_impl ()
executes tasks
virtual hryky::task::worker::Batch< TaskT >::~Batch ()
destructor
virtual hryky::task::distributor::Batch< TaskT >::~Batch ()
destructor
virtual hryky::task::distributor::Impl< WorkerT >::~Impl ()
destructor.
Detailed Description
modules to execute multiple tasks concurrently.
Function Documentation
template<typename TaskT > bool hryky::task::worker::Batch< TaskT >::append (task_const_reference task)
appends a task.
Parameters
task is a unit of execution.
References hryky_log_err, and hryky::reduction::map().
template<typename TaskT > template<typename InputIterator > bool hryky::task::worker::Batch< TaskT >::append (InputIterator begin, InputIterator end)
appends multiple tasks.
Parameters
begin is the beginning of the container of tasks.
end is the end of the container of tasks.
Attention
the range of the array of tasks is [begin, end)
References hryky_log_err, and hryky::reduction::map().
template<typename TaskT > bool hryky::task::distributor::Batch< TaskT >::attach_with (task_const_reference task)
appends and executes a task.
distributes a task to a worker and executes the task.
Parameters
task is an executable task.
References hryky::task::worker::Base::attach(), hryky_log_err, and hryky::reduction::map().
template<typename TaskT > hryky::task::worker::Batch< TaskT >::Batch () [explicit]
default constructor
default constructor.
template<typename TaskT > hryky::task::distributor::Batch< TaskT >::Batch ()
default constructor
default constructor.
References hryky::task::distributor::Base::WorkerObserver::distributor().
template<typename TaskT > bool hryky::task::distributor::Batch< TaskT >::distribute (task_const_reference task)
passes a task to a worker.
Parameters
task is an executable task.
Returns
success or failure.
Attention
This function merely distributes a task to a worker. Until the worker is assigned to the thread execution, the task will not be executed.
References hryky_log_err, and hryky::reduction::map().
template<typename TaskT > template<typename InputIterator > bool hryky::task::distributor::Batch< TaskT >::distribute (InputIterator begin, InputIterator end)
passes multiple tasks to workers.
Parameters
begin is the beginning of the container of tasks.
end is the beginning of the container of tasks.
Returns
success or failure.
References hryky_log_err, and hryky::reduction::map().
template<typename TaskT > bool hryky::task::distributor::Batch< TaskT >::reset (ResetParameter const & param)
clears and recreates the resources.
Parameters
param is the set of parameters to reset.
Returns
failure and success.
Reimplemented from hryky::task::distributor::Base.
References hryky::Vector< ValueT, AllocatorT >::begin(), hryky::memory::global::heap(), hryky_log_err, HRYKY_NULLPTR, hryky::reduction::map(), hryky::task::worker::Base::reset(), hryky::Vector< ValueT, AllocatorT >::resize(), hryky::task::Concurrency::sequence(), and hryky::task::Concurrency::units_size().
template<typename TaskT > bool hryky::task::worker::Batch< TaskT >::reset (ResetParameter const & param)
clears and recreates resources.
Returns
failure and success
Reimplemented from hryky::task::worker::Base.
References hryky::clear(), hryky::memory::global::heap(), hryky_log_err, HRYKY_NULLPTR, hryky::hryky_swap(), hryky::reduction::map(), and hryky::Vector< ValueT, AllocatorT >::reserve().
template<typename TaskT > void hryky::task::worker::Batch< TaskT >::run_impl () [protected, virtual]
executes tasks
executes tasks.
Implements hryky::task::worker::Base.
References hryky::dereference().
template<typename TaskT > hryky::task::worker::Batch< TaskT >::~Batch () [virtual]
destructor
destructor.
References hryky::clear().
template<typename TaskT > hryky::task::distributor::Batch< TaskT >::~Batch () [virtual]
destructor
destructor.