hryky::http Namespace Reference
modules to manage HTTP.
Classes
class Entity
retains the information about a HTTP Message.
class Parser
writes out a HTTP Message.
class Stream
writes and writes HTTP Message.
Functions
bool is_separator (octet_type const octet)
confirms that an octet is a separator of HTTP.
bool is_text_char (octet_type const octet)
confirms that an octet belongs to the characters of TEXT.
bool is_token_char (octet_type const octet)
confirms that an octet belongs to the character of token.
reduction_type reduce (reduction::name_type const &name, Entity const &src)
decomposes the instance to primitive objects.
reduction_type reduce (reduction::name_type const &name, Parser const &src)
decomposes the instance to primitive objects.
void swap (Entity &lhs, Entity &rhs)
interchanges two instances of same type.
void swap (Parser &lhs, Parser &rhs)
interchanges two instances of same type.
Detailed Description
modules to manage HTTP.
Function Documentation
void hryky::http::swap (Entity & lhs, Entity & rhs)
interchanges two instances of same type.
interchanges two instances of the same type.
References hryky::http::Entity::swap().
Referenced by hryky::http::header::field::dispatcher::Apply::swap(), hryky::http::header::product_comment::dispatcher::Apply< ReceiverT >::swap(), hryky::http::header::cache::directive::dispatcher::Apply::swap(), and hryky::http::header::Parser::swap().
void hryky::http::swap (Parser & lhs, Parser & rhs)
interchanges two instances of same type.
interchanges two instances of the same type.
References hryky::http::Parser::swap().