hryky::reduction Namespace Reference
modules to format the output string.
Classes
class Address
primitive type of reduction as memory address.
class Array
aggregates the multiple values without their names.
class Base
the interface of decomposing.
class Bool
primitive type of reduction as boolean.
class Char
primitive type of reduction for char.
class Dispatcher
dispatches the each implementation of hryky::reduction::Base.
class Float
primitive type of reduction as floating point.
class Int
primitive type of reduction as signed integer.
class Map
aggregates the multiple named values with each name.
class Stream
traverses the decomposed structure.
class String
primitive type of reduction as string.
class Uint
primitive type of reduction as unsigned integer.
Typedefs
typedef IntrusivePtr< Array > array_type
type to use reduction::Array
typedef IntrusivePtr< Map > map_type
type to use reduction::Map
typedef string_type name_type
name of each format element
typedef String< char,
*
allocator::Heap< char,
*
memory::heap::Base * > > string_type
type of string
Functions
array_type array (name_type const &name)
creates an instance of reduction::Array.
template<size_t Size>
array_type array (char const (&name)[Size])
creates an instance of reduction::Array.
void intrusive_ptr_add_ref (Base *ptr)
increments the reference counter.
void intrusive_ptr_release (Base *ptr)
decrements the reference counter.
map_type map (name_type const &name)
creates an instance of reduction::Map.
template<size_t Size>
map_type map (char const (&name)[Size])
creates an instance of reduction::Map.
map_type map ()
creates an instance of reduction::Map without name.
reduction_type reduce (reduction::name_type const &name, Dispatcher const &src)
decomposes the instance to primitive objects.
template<typename ValueT >
reduction_type reduce (reduction::name_type const &name, ValueT const value, typename EnableIf< IsUnsigned< ValueT > >::type *=HRYKY_NULLPTR)
creates a primitive object decomposed as 64bit unsigned integer.
template<typename StreamT >
reduction_type reduce (reduction::name_type const &name, Stream< StreamT > const &src)
decomposes the instance to primitive objects.
void swap (Uint &lhs, Uint &rhs)
interchanges two instances of same type.
void swap (Address &lhs, Address &rhs)
interchanges two instances of same type.
void swap (Bool &lhs, Bool &rhs)
interchanges two instances of same type.
void swap (Char &lhs, Char &rhs)
interchanges two instances of same type.
void swap (Float &lhs, Float &rhs)
interchanges two instances of same type.
void swap (Dispatcher &lhs, Dispatcher &rhs)
interchanges two instances of same type.
void swap (Array &lhs, Array &rhs)
interchanges two instances of same type.
void swap (Int &lhs, Int &rhs)
interchanges two instances of same type.
void swap (String &lhs, String &rhs)
interchanges two instances of same type.
void swap (Map &lhs, Map &rhs)
interchanges two instances of the same type.
template<typename StreamT >
void swap (Stream< StreamT > &lhs, Stream< StreamT > &rhs)
interchanges two instances of same type.
Detailed Description
modules to format the output string.
Function Documentation
hryky::reduction::map_type hryky::reduction::map (name_type const & name)
creates an instance of reduction::Map.
Parameters
name is the name of the instance.
Returns
the instance.
Examples:
test_log.cpp, test_main.cpp, test_memory_heap_arbitrary.cpp, test_memory_heap_fixed.cpp, test_task_hello.cpp, and test_task_quicksort.cpp.
Referenced by hryky::memory::heap::Arbitrary< OffsetT >::allocatable_size(), hryky::memory::heap::Arbitrary< OffsetT >::allocate(), hryky::http::header::connection::Entity::append(), hryky::http::header::cache::control::Entity::append(), hryky::task::worker::Batch< TaskT >::append(), hryky::task::distributor::Batch< TaskT >::attach_with(), hryky::opengl::check_gl(), hryky::memory::heap::Fixed::deallocate(), hryky::memory::heap::Arbitrary< OffsetT >::deallocate(), hryky::task::distributor::Batch< TaskT >::distribute(), hryky::Substring< OriginT, OffsetT, ValueT >::find(), hryky::thread::Resource::ideal_processor(), map(), hryky::file::descriptor::Entity::open(), hryky::opengl::reduce(), hryky::writer::Base::reduce(), hryky::task::distributor::Impl< WorkerT >::reduce(), hryky::reduction::Dispatcher::reduce(), hryky::http::header::field::Base::reduce(), hryky::http::header::cache::directive::Base::reduce(), hryky::http::header::field::dispatcher::Apply::reduce(), hryky::file::descriptor::Mode::reduce(), hryky::http::Entity::reduce(), hryky::NarrowToken< ResultT, Size >::reduce(), hryky::display::Traverser::reduce(), hryky::date::Entity::reduce(), hryky::reduction::Stream< StreamT >::reduce(), hryky::http::seconds::Entity::reduce(), hryky::http::Parser::reduce(), hryky::Foreach< ContainerT, IteratorT >::reduce(), hryky::http::version::Entity::reduce(), hryky::Adapter< BaseT, ValueT >::reduce(), hryky::http::header::comment::Base::reduce(), hryky::http::header::connection::Entity::reduce(), hryky::uri::hierarchy::Entity::reduce(), hryky::http::body::Entity::reduce(), hryky::http::header::date::Entity::reduce(), hryky::http::header::Entity::reduce(), hryky::http::header::parameter::Entity::reduce(), hryky::file::descriptor::Entity::reduce(), hryky::uri::host::Entity::reduce(), hryky::uri::path::Entity::reduce(), hryky::http::header::language::Entity::reduce(), hryky::http::header::host::Entity::reduce(), hryky::http::header::media_type::Entity::reduce(), hryky::http::header::product_comment::Base::reduce(), hryky::http::header::server::Entity::reduce(), hryky::type::Info::reduce(), hryky::uri::Entity::reduce(), hryky::http::header::field::extension::Entity::reduce(), hryky::http::header::accept::extension::Entity::reduce(), hryky::http::header::user_agent::Entity::reduce(), hryky::http::header::accept::content::Entity::reduce(), hryky::http::header::cache::directive::Second::reduce(), hryky::http::header::accept::charset::content::Entity::reduce(), hryky::parser::Base< GeneratedT >::reduce(), hryky::http::header::accept::params::Entity::reduce(), hryky::http::header::cache::control::Entity::reduce(), hryky::http::header::cache::directive::Field::reduce(), hryky::http::header::accept::encoding::content::Entity::reduce(), hryky::http::header::accept::language::content::Entity::reduce(), hryky::http::header::product_comment::dispatcher::Base::reduce(), hryky::http::header::product::Entity::reduce(), hryky::http::request::line::Entity::reduce(), hryky::uri::authority::Entity::reduce(), hryky::display::Screen::reduce(), hryky::http::header::cache::directive::dispatcher::Apply::reduce(), hryky::Index< IntT >::reduce(), hryky::ip::v6::Entity::reduce(), hryky::Indent::reduce(), hryky::uri::Parser::reduce(), hryky::http::header::cache::directive::dispatcher::Base::reduce(), hryky::http::header::Parser::reduce(), hryky::ip::v4::Entity::reduce(), hryky::http::request::Entity::reduce(), hryky::thread::Resource::reduce(), hryky::thread::Pool::reduce(), hryky::Substring< OriginT, OffsetT, ValueT >::reduce(), hryky::task::Concurrency::reduce(), hryky::testing::reduce(), hryky::display::Mode::reduce(), hryky::exclusion::Counter::reduce(), hryky::Any< AllocatorT >::reduce(), hryky::http::header::field::dispatcher::Base::reduce(), hryky::memory::heap::Fixed::reduce(), hryky::reduce(), hryky::display::reduce(), hryky::memory::heap::Arbitrary< OffsetT >::reduce(), hryky::random::distribution::reduce(), hryky::task::worker::reduce(), hryky::String< CharT, AllocatorT >::reduce(), hryky::memory::heap::Fixed::reset(), hryky::task::Concurrency::reset(), hryky::display::Screen::reset(), hryky::task::distributor::Batch< TaskT >::reset(), hryky::task::distributor::Base::reset(), hryky::task::worker::Batch< TaskT >::reset(), hryky::memory::heap::Arbitrary< OffsetT >::reset(), hryky::ip::v6::Entity::segment(), hryky::ip::v4::Entity::segment(), hryky::Substring< OriginT, OffsetT, ValueT >::substr(), hryky::parser::Base< GeneratedT >::trace(), hryky::memory::heap::Fixed::verify(), and hryky::memory::heap::Arbitrary< OffsetT >::verify().
hryky::reduction::map_type hryky::reduction::map ()
creates an instance of reduction::Map without name.
Returns
the instance.
template<typename ValueT > hryky::reduction_type hryky::reduction::reduce (reduction::name_type const & name, ValueT const value, typename EnableIf< IsUnsigned< ValueT > >::type * = HRYKY_NULLPTR)
creates a primitive object decomposed as 64bit unsigned integer.
creates a primitive object decomposed as unsigned integer.
void hryky::reduction::swap (Uint & lhs, Uint & rhs)
interchanges two instances of same type.
interchanges two instances of the same type.
References hryky::reduction::Uint::swap().
void hryky::reduction::swap (Address & lhs, Address & rhs)
interchanges two instances of same type.
interchanges two instances of the same type.
References hryky::reduction::Address::swap().
Referenced by hryky::reduction::Address::swap(), hryky::reduction::Bool::swap(), hryky::reduction::Char::swap(), hryky::reduction::Float::swap(), hryky::reduction::Int::swap(), hryky::reduction::Stream< StreamT >::swap(), hryky::reduction::Uint::swap(), hryky::reduction::String::swap(), hryky::reduction::Array::swap(), and hryky::reduction::Map::swap().
void hryky::reduction::swap (Bool & lhs, Bool & rhs)
interchanges two instances of same type.
interchanges two instances of the same type.
References hryky::reduction::Bool::swap().
void hryky::reduction::swap (Char & lhs, Char & rhs)
interchanges two instances of same type.
interchanges two instances of the same type.
References hryky::reduction::Char::swap().
void hryky::reduction::swap (Float & lhs, Float & rhs)
interchanges two instances of same type.
interchanges two instances of the same type.
References hryky::reduction::Float::swap().
void hryky::reduction::swap (Dispatcher & lhs, Dispatcher & rhs)
interchanges two instances of same type.
interchanges two instances of the same type.
References hryky::reduction::Dispatcher::swap().
void hryky::reduction::swap (Array & lhs, Array & rhs)
interchanges two instances of same type.
interchanges two instances of the same type.
References hryky::reduction::Array::swap().
void hryky::reduction::swap (Int & lhs, Int & rhs)
interchanges two instances of same type.
interchanges two instances of the same type.
References hryky::reduction::Int::swap().
void hryky::reduction::swap (String & lhs, String & rhs)
interchanges two instances of same type.
interchanges two instances of the same type.
References hryky::reduction::String::swap().
template<typename StreamT > void hryky::reduction::swap (Stream< StreamT > & lhs, Stream< StreamT > & rhs)
interchanges two instances of same type.
interchanges two instances of the same type.
References hryky::reduction::Stream< StreamT >::swap().