hryky::log::format Namespace Reference
modules to format the output string.
Classes
class Base
the interface of logging format.
class Map
aggregates the multiple named values with each name.
class Value
holds the value to log.
Typedefs
typedef IntrusivePtr< Map > map_type
type to use log::format::Map
typedef string_type name_type
name of each format element
typedef std::string string_type
type of string
Functions
void intrusive_ptr_add_ref (Base *ptr)
increments the reference counter.
void intrusive_ptr_release (Base *ptr)
decrements the reference counter.
template<typename ValueT >
format_type make_format (format::name_type const &name, ValueT const &value)
creates the derived instance of log::format::Base corresponding to parameter.
format_type make_format (name_type const &name, char const *&str)
outputs the null-terminated string with key.
template<size_t Size>
format_type make_format (name_type const &name, char const (&str)[Size])
outputs the array of characters with the name.
log::format_type make_format (name_type const &name, uint8_t const &src)
outputs an uint8_t as a value.
map_type map (name_type const &name)
creates an instance of log::format::Map.
map_type map ()
creates an instance of log::format::Map without name.
std::ostream & operator<< (std::ostream &lhs, Base const &rhs)
print information.
template<typename ValueT >
format_type value (name_type const &name, ValueT const &src)
instantiates log::format::Value.
Detailed Description
modules to format the output string.
Function Documentation
template<typename ValueT > hryky::log::format_type hryky::log::format::make_format (format::name_type const & name, ValueT const & value)
creates the derived instance of log::format::Base corresponding to parameter.
Parameters
name is the name of the information.
value is the value held by the instance.
Returns
the instance.
Attention
You have to overload this function which is passed the value as the second argument.
Since
2011-12-30T09:51:54+0900
Parameters
name is the name of the param.
value is the value to be outputed
Referenced by hryky::log::format::Map::append(), and value().
hryky::log::format_type hryky::log::format::make_format (name_type const & name, char const *& str) [inline]
outputs the null-terminated string with key.
Since
2012-05-03T19:01:24+0900
Parameters
name is the name of the param.
str is the value to be outputed
This functions is overload of make_format() for null-terminated string.
template<size_t Size> hryky::log::format_type hryky::log::format::make_format (name_type const & name, char const (&) str[Size])
outputs the array of characters with the name.
Since
2012-05-19T14:48:18+0900
Parameters
name is the name of the param.
str is the value to be outputed
This functions is overload of make_format() for the array of characters.
hryky::log::format_type hryky::log::format::make_format (name_type const & name, uint8_t const & src) [inline]
outputs an uint8_t as a value.
Since
2012-08-27T23:40:42+0900
map_type hryky::log::format::map (name_type const & name)
creates an instance of log::format::Map.
Parameters
name is the name of the instance.
Returns
the instance.
Examples:
test_log.cpp, test_memory_heap_arbitrary.cpp, test_memory_heap_fixed.cpp, test_task_hello.cpp, and test_task_quicksort.cpp.
Referenced by hryky::task::worker::Batch< TaskT >::append(), hryky::task::distributor::Batch< TaskT >::attach_with(), hryky::opengl::check_gl(), hryky::task::distributor::Batch< TaskT >::distribute(), hryky::Substring< OriginT, OffsetT, ValueT >::find(), hryky::task::distributor::Impl< WorkerT >::log(), hryky::Foreach< ContainerT, IteratorT >::log(), hryky::Substring< OriginT, OffsetT, ValueT >::log(), hryky::String< CharT, AllocatorT >::log(), hryky::geometry::make_format(), hryky::make_format(), hryky::random::distribution::make_format(), hryky::task::worker::make_format(), hryky::task::distributor::Batch< TaskT >::reset(), hryky::task::worker::Batch< TaskT >::reset(), and hryky::Substring< OriginT, OffsetT, ValueT >::substr().
map_type hryky::log::format::map ()
creates an instance of log::format::Map without name.
Returns
the instance.
template<typename ValueT > hryky::log::format_type hryky::log::format::value (name_type const & name, ValueT const & src)
instantiates log::format::Value.
Parameters
name is the name of value.
src is the value held by the instance.
Returns
the instance.
Since
2012-01-08T13:16:33+0900
Examples:
test_log.cpp, and test_task_quicksort.cpp.
References make_format().
Referenced by hryky::align_floor(), hryky::FixedVector< ValueT, Capacity >::assign(), hryky::FixedVector< ValueT, Capacity >::insert(), hryky::String< CharT, AllocatorT >::insert(), hryky::exclusion::Atomic< ValueT, LockableT >::operator value_type(), hryky::exclusion::AtomicWriting< ValueT, LockableT >::operator++(), hryky::exclusion::Atomic< ValueT, LockableT >::operator++(), hryky::exclusion::AtomicWriting< ValueT, LockableT >::operator--(), hryky::exclusion::Atomic< ValueT, LockableT >::operator--(), hryky::qsort_internal::pivot_position(), hryky::String< CharT, AllocatorT >::push_back(), and hryky::qsort().