hryky::qsort_internal Namespace Reference
internal use of qsort()
Functions
template<typename InputIterator >
InputIterator partition (InputIterator const begin, InputIterator const end)
divides into two groups.
template<typename InputIterator >
size_t pivot_position (InputIterator const begin, InputIterator const end)
gets the position of pivot to partition values.
Detailed Description
internal use of qsort()
Function Documentation
template<typename InputIterator > InputIterator hryky::qsort_internal::partition (InputIterator const begin, InputIterator const end)
divides into two groups.
divides into two groups. The values in one group are less than a pivot. The values in the other is equal to or greater than the pivot.
Parameters
begin specifies the beginning of the sorted range.
end specifies just after the last element in the sorted range.
Returns
The beginning of the last half gruop.
divides into two groups. The values in one group are less than a pivot. The values in the other is equal to or greater than the pivot.
Examples:
test_task_quicksort.cpp.
References hryky::hryky_swap(), and pivot_position().
Referenced by hryky::qsort().
template<typename InputIterator > size_t hryky::qsort_internal::pivot_position (InputIterator const begin, InputIterator const end)
gets the position of pivot to partition values.
Parameters
begin specifies the beginning of the sorted range.
end specifies just after the last element in the sorted range.
Return values
-1 represents that all elements in the range are same value.
!=-1 represents the position of the element selected as the target of comparison (known as pivot).
References hryky::Foreach< ContainerT, IteratorT >::offset(), and hryky::range().
Referenced by partition().