hryky Namespace Reference
the root of all namespaces in hryky-codebase.
Namespaces
namespace atomic
modules for atomic operation.
namespace chrono
The modules for dealing with duration time.
namespace display
modules for modulation of the configuration of display device.
namespace error
modules to handle errors.
namespace exclusion
modules for exclusion control.
namespace geometry
modules for processing geometry.
namespace graphics
modules of respect to graphics processing.
namespace http
modules to manage HTTP.
namespace log
modules for logging progress.
namespace memory
modules to manage memory allocation.
namespace opengl
modules to wrap the interfaces of OpenGL API.
namespace parser
utilities to use parsers generated by parser generator.
namespace pixcel
modules for processing pixel format.
namespace qsort_internal
internal use of qsort()
namespace random
modules to generate pseudo-random number.
namespace reduction
modules to format the output string.
namespace scale
The modules for dealing with unit systems.
namespace task
modules for running tasks concurrently.
namespace testing
modules for testing
namespace thread
modules for managing concurrent resources.
namespace uri
modules to handle URI.
Classes
class Adapter
provides the interface in behalf of the valueementation.
class AddConst
add const qualifier.
class AddConstPointer
retrieves the traits as const pointer from any type.
class AddConstReference
retrieves the traits as const reference from any type.
class AddPointer
retrieves the traits as pointer from any type .
class AddReference
retrieves the traits as reference from any type.
class And
retrieves the logical multiply (AND operation) between two generic types.
class Any
arbitrary typed value without polymorphism.
class Array
substitutes for std::array.
class AsParameter
retrieves the type as parameter of function.
class Assignable
define assignment in which swap is used.
class AutoDelete
delete an instance when the current scope exits.
struct AutoFree
deallocate a pointer when the current scope exits.
struct AutoFunc
calls a function when the current scope exits.
struct AutoFunc1
calls a function when the current scope exits.
struct AutoFunc2
calls a function when the current scope exits.
struct AutoRelease
releases a resource when the current scope exits.
class Bitfield
initializes and clears bitfields.
class Bitset
bitset of fixed size on compile time.
class Copyable
base class to copy the information of derived class.
class DisableIf
substitutes for std::disable_if.
class DisableIfC
substitutes for std::disable_if_c.
class EnableIf
substitutes for std::enable_if.
class EnableIfC
substitutes for std::enable_if_c.
class FixedVector
vector of fixed size on compile time.
class Foreach
utility for the iteration of a container.
class HasClear
confirms whether the class has 'clear' function.
class HasConstIterator
confirms whether a container has const_iterator.
class HasHigher
workaround for msvc10 internal compile error.
class Indent
indents a line of log.
class Index
iterates the range of integer numbers.
class IntrusivePtr
basic functionality of intrusive pointer.
class IsAsString
confirms whether a class can be used as string.
class IsBaseOf
confirms whether two types are in the inheritance relationship.
class IsChar
confirmes whether the type is char.
class IsChar< char >
specializes IsChar of which the argument is char.
class IsEnum
confirms whether the type is enum in compile time..
class IsFloatingPoint
confirms whether a type is builtin floating point.
class IsInteger
confirms wheter the type is integer.
class IsNumeric
confirmes whether the type is numeric.
class IsSame
confirms whether two types are same.
class IsSame< ValueT, ValueT >
specializes IsSame of which arguments are same.
class IsSigned
confirms whether a type is signed type.
class IsSigned< int16_t >
specializes int16_t.
class IsSigned< int32_t >
specializes int32_t.
class IsSigned< int64_t >
specializes int64_t.
class IsSigned< int8_t >
specializes int8_t.
class IsSigned< int_t >
specializes int64_t.
class IsUnsigned
confirms whether a type is unsigned.
class IsUnsigned< uint16_t >
specializes uint16_t.
class IsUnsigned< uint32_t >
specializes uint32_t.
class IsUnsigned< uint8_t >
specializes uint8_t.
class IteratorOf
retrieves the type of iterator from a container.
class Kind
template for the class that represents the kind.
class LiteralString
retains a literal string and its length.
class MaxOf
retrieves the maximum value.
class MinOf
retrieves the maximum value.
class NarrowToken
narrows down candidates by sequence of values.
class Noncopyable
forbid copy of class instance.
struct Not
reverse the member variable of boolean value.
struct NotC
reverses the boolean value.
class Null
no-effective type.
class OffsetPtr
refers the value by the offset from the origin.
class Or
retrieves the logical add (OR operation) between two generic types.
class Placementnewable
enable class to use placement-new.
class Placementnewonly
allows class to use only placement new/delete.
class Range
mediates the characteristic which has begin() and end().
class RemoveConst
removes const qualifier.
class RemoveConst< const ValueT >
specialize RemoveConst for the type which has const qualifier.
class RemovePointer
dereferences the pointer of any type.
class ScopedArray
array with the size.
class Sequence
retains multiple arbitrary values.
class Sequence1
sequence which has one value.
class Sequence2
sequence which has two values.
class Sequence3
sequence which has three values.
class Sequence4
sequence which has 4 values.
class Sequence< FirstT, hryky::Null >
specialization of hryky::Sequence which has only one value.
class Sequence< hryky::Null, hryky::Null >
specialization of hryky::Sequence which has no value.
class SharedPtr
smart pointer which has a reference count.
class SignedBitsEnough
retrieves the bit width in which a signed value of specified size can be stored.
class SignedEnoughBytes
retrieves the type of signed integer which has the capacity of the specified size.
class SignedEnoughExponent
retrieves the type of signed integer which has the capacity of the specified exponent.
class String
substitutes for std::string.
class Substring
represents the part of string.
class UnsignedBitsEnough
retrieves the bit width in which a unsigned value of specified size can be stored.
class UnsignedEnoughBytes
retrieves the type of unsigned integer which has the capacity of the specified byte size.
class UnsignedEnoughExponent
retrieves the type of unsigned integer which has the capacity of the specified exponent.
class Vector
substitutes for std::vector container.
Typedefs
typedef uint8_t alignment_type
represents an alignment in bits.
typedef int(* main_func_pointer)(int, char const *const [])
utility type to pass a function pointer to hryky::main().
typedef uint8_t octet_type
alias for 8bit data.
typedef uint32_t processor_id_type
an identifier of processor.
typedef IntrusivePtr
*
< reduction::Base > reduction_type
type of the interface to format each parameter
Functions
template<typename T >
T align_ceil (T value, alignment_type alignment)
rounds up an integer value to the nearest value aligned in bit.
template<typename T >
T align_floor (T value, alignment_type alignment)
rounds down an integer value to the nearest value aligned in bit.
template<typename ValueT >
void clear (ValueT &value, typename EnableIf< HasClear< ValueT > >::type *=HRYKY_NULLPTR)
clears an arbitrary instance which has 'clear' function.
template<typename ValueT >
void clear (ValueT &value, typename DisableIf< HasClear< ValueT > >::type *=HRYKY_NULLPTR)
clears an arbitrary instance which doesn't have 'clear' function.
template<typename ValueT >
RemovePointer< ValueT * >
*
::result_type dereference (ValueT *src)
dereferences the pointer of any type.
template<typename ValueT >
RemovePointer< ValueT >
*
::result_type dereference (ValueT &src)
returns an argument directly as reference.
size_t hamming_weight (uint64_t const value)
counts the number of non-zero bit in 64 bits value.
template<typename ValueT >
void hryky_swap (ValueT &lhs, ValueT &rhs)
interchanges entities of two instances.
template<typename AllocatorT >
AllocatorT::pointer instantiate (AllocatorT &allocator)
allocates a memory and instantiates in the memory.
template<typename AllocatorT , typename Arg1T >
AllocatorT::pointer instantiate (AllocatorT &allocator, Arg1T const &arg1)
allocates a memory and instantiates in the memory with one argument.
template<typename AllocatorT , typename Arg1T , typename Arg2T >
AllocatorT::pointer instantiate (AllocatorT &allocator, Arg1T const &arg1, Arg2T const &arg2)
allocates a memory and instantiates in the memory with two arguments.
template<typename T >
bool is_aligned (T value, alignment_type alignment)
confirms whether an integer value is aligned in bit
template<typename MainFuncT >
int main (int argc, char const *const argv[], typename AsParameter< MainFuncT >::type func)
wrapper function to catch exception.
int main (int argc, char const *const argv[], main_func_pointer func)
wrapper function to catch exception.
void * memset (void *dest, int octet, std::size_t const count)
fills memory with a octet.
template<typename CharT , typename AllocatorT >
bool operator!= (CharT const *const lhs, String< CharT, AllocatorT > const &rhs)
confirms whether a null-terminated character is not equal to a string.
template<typename CharT , typename AllocatorT >
bool operator< (CharT const *const lhs, String< CharT, AllocatorT > const &rhs)
confirms whether a null-terminated character is less than a string.
template<typename CharT , typename AllocatorT >
bool operator<= (CharT const *const lhs, String< CharT, AllocatorT > const &rhs)
confirms whether a null-terminated character is less than or equal to a string.
template<typename CharT , typename AllocatorT >
bool operator== (CharT const *const lhs, String< CharT, AllocatorT > const &rhs)
confirms whether a null-terminated character is equal to a string.
template<typename CharT , typename AllocatorT >
bool operator> (CharT const *const lhs, String< CharT, AllocatorT > const &rhs)
confirms whether a null-terminated character is greater than a string.
template<typename CharT , typename AllocatorT >
bool operator>= (CharT const *const lhs, String< CharT, AllocatorT > const &rhs)
confirms whether a null-terminated character is greater than or equal to a string.
template<typename InputIterator >
void qsort (InputIterator const begin, InputIterator const end)
quick sort.
template<typename IteratorT >
Range< IteratorT > range (IteratorT begin, IteratorT end)
creates hryky::Range.
template<typename ValueT , size_t Size>
Range< ValueT * > range (ValueT(&array)[Size])
creates hryky::Range from an array.
template<typename ValueT >
reduction_type reduce (reduction::name_type const &name, ScopedArray< ValueT > const &array)
outputs the information of hryky::ScopedArray.
template<typename IteratorT >
reduction_type reduce (reduction::name_type const &name, Range< IteratorT > const &range)
creates reduction_type to output the information of hryky::Range.
template<typename Rep , typename Period >
hryky::reduction_type reduce (reduction::name_type const &name, std::chrono::duration< Rep, Period > const &src)
decomposes the instance to primitive objects.
reduction_type reduce (reduction::name_type const &name, thread::id_type const &src)
decomposes std::thread::id to string.
reduction_type reduce (reduction::name_type const &name, bool value)
creates a primitive object decomposed as boolean.
reduction_type reduce (reduction::name_type const &name, void const *value)
creates a primitive object decomposed as memory address.
template<typename ValueT >
reduction_type reduce (reduction::name_type const &name, ValueT const value, typename EnableIf< IsChar< ValueT > >::type *=HRYKY_NULLPTR)
creates a primitive object decomposed as char.
template<typename ValueT >
reduction_type reduce (reduction::name_type const &name, ValueT const value, typename EnableIf< IsFloatingPoint< ValueT > >::type *=HRYKY_NULLPTR)
creates a primitive object decomposed as floating point.
template<typename ValueT >
reduction_type reduce (reduction::name_type const &name, ValueT const value, typename EnableIf< IsSigned< ValueT > >::type *=HRYKY_NULLPTR)
creates a primitive object decomposed as signed integer.
template<typename ValueT >
reduction_type reduce (reduction::name_type const &name, ValueT value, typename EnableIf< IsEnum< ValueT > >::type *=HRYKY_NULLPTR)
creates a primitive object decomposed as int.
reduction_type reduce (reduction::name_type const &name, char const *const &value)
template<size_t Size>
reduction_type reduce (reduction::name_type const &name, char const (&src)[Size])
reduction_type reduce (reduction::name_type const &name, Indent const &src)
decomposes the instance to primitive objects.
template<typename ValueT , size_t Size>
reduction_type reduce (reduction::name_type const &name, Array< ValueT, Size > const &src)
outputs the information formatted as string.
reduction_type reduce (reduction::name_type const &name, LiteralString const &src)
decomposes the instance to primitive objects.
template<typename BaseT , typename ValueT >
reduction_type reduce (reduction::name_type const &name, Adapter< BaseT, ValueT > const &src)
decomposes the instance to primitive objects.
template<typename BitsT >
reduction_type reduce (reduction::name_type const &name, Bitfield< BitsT > const &src)
decomposes the instance to primitive objects.
template<typename RawT , typename RawT::Raw Initial>
reduction_type reduce (reduction::name_type const &name, Kind< RawT, Initial > const &src)
decomposes the instance to primitive objects.
template<typename RawT , typename RawT::Raw Initial, size_t Size>
reduction_type reduce (char const (&name)[Size], Kind< RawT, Initial > const &src)
decomposes the instance to primitive objects.
template<typename IntT >
reduction_type reduce (reduction::name_type const &name, Index< IntT > const &src)
decomposes the instance to primitive objects.
template<typename ResultT , size_t Size>
reduction_type reduce (reduction::name_type const &name, NarrowToken< ResultT, Size > const &src)
decomposes the instance to primitive objects.
template<typename OriginT , typename OffsetT , typename ValueT >
reduction_type reduce (reduction::name_type const &name, Substring< OriginT, OffsetT, ValueT > const &src)
formats the information of the Substring.
template<typename ContainerT , typename IteratorT >
reduction_type reduce (reduction::name_type const &name, Foreach< ContainerT, IteratorT > const &src)
outputs the information formatted as string.
template<typename ValueT , typename LockableT , typename AllocatorT >
hryky::reduction_type reduce (reduction::name_type const &name, SharedPtr< ValueT, LockableT, AllocatorT > const &src)
decomposes the instance to primitive objects.
template<typename AllocatorT >
reduction_type reduce (reduction::name_type const &name, Any< AllocatorT > const &src)
decomposes the instance to primitive objects.
template<size_t BitsSize>
reduction_type reduce (reduction::name_type const &name, Bitset< BitsSize > const &src)
decomposes the instance to primitive objects.
template<typename ValueT , size_t Capacity>
reduction_type reduce (reduction::name_type const &name, FixedVector< ValueT, Capacity > const &vector)
outputs the information of hryky::FixedVector.
template<typename ValueT , typename AllocatorT >
reduction_type reduce (reduction::name_type const &name, Vector< ValueT, AllocatorT > const &vector)
outputs the information of hryky::Vector.
template<typename CharT , typename AllocatorT >
reduction_type reduce (reduction::name_type const &name, String< CharT, AllocatorT > const &src)
outputs the information formatted as string.
template<typename AllocatorT >
void release (AllocatorT &allocator, typename AllocatorT::pointer instance)
destroys an instance and deallocates the memory which the instance is on.
template<typename T >
void release (T *&ptr)
release the instance that has release() method.
template<typename Arg1T >
Sequence1< Arg1T > sequence1 (Arg1T const &arg1)
creates a sequence which has one value.
template<typename Arg1T , typename Arg2T >
Sequence2< Arg1T, Arg2T > sequence2 (Arg1T const &arg1, Arg2T const &arg2)
creates a sequence which has two values.
template<typename Arg1T , typename Arg2T , typename Arg3T >
Sequence3< Arg1T, Arg2T, Arg3T > sequence3 (Arg1T const &arg1, Arg2T const &arg2, Arg3T const &arg3)
creates a sequence which has three values.
template<typename Arg1T , typename Arg2T , typename Arg3T , typename Arg4T >
Sequence4< Arg1T, Arg2T, Arg3T,
*
Arg4T > sequence4 (Arg1T const &arg1, Arg2T const &arg2, Arg3T const &arg3, Arg4T const &arg4)
creates a sequence which has 4values.
template<typename DerivedT >
void swap (Assignable< DerivedT > &lhs, Assignable< DerivedT > &rhs)
interchanges the entities of two instances.
template<typename ValueT >
void swap (ScopedArray< ValueT > &lhs, ScopedArray< ValueT > &rhs)
interchanges the entities of two instances.
template<typename DerivedT >
void swap (DerivedT &src, DerivedT &src)
interchanges two instances of same type.
template<typename ValueT , size_t Size>
void swap (Array< ValueT, Size > &lhs, Array< ValueT, Size > &rhs)
interchanges values.
void swap (Indent &lhs, Indent &rhs)
interchanges two instances of the same type.
void swap (LiteralString &lhs, LiteralString &rhs)
interchanges two instances of the same type.
template<typename BaseT , typename ValueT >
void swap (Adapter< BaseT, ValueT > &lhs, Adapter< BaseT, ValueT > &rhs)
interchanges two instances of same type.
template<typename BitsT >
void swap (Bitfield< BitsT > &lhs, Bitfield< BitsT > &rhs)
interchanges two instances of same type.
template<typename RawT , typename RawT::Raw Initial>
void swap (Kind< RawT, Initial > &lhs, Kind< RawT, Initial > &rhs)
interchanges two instances of the same type.
template<typename IntT >
void swap (Index< IntT > &lhs, Index< IntT > &rhs)
interchanges two instances of same type.
template<typename ResultT , size_t Size>
void swap (NarrowToken< ResultT, Size > &lhs, NarrowToken< ResultT, Size > &rhs)
interchanges two instances of same type.
template<typename ContainerT , typename IteratorT >
void swap (Foreach< ContainerT, IteratorT > &lhs, Foreach< ContainerT, IteratorT > &rhs)
interchanges two instances of the same type.
template<typename OriginT , typename OffsetT , typename ValueT >
void swap (OffsetPtr< OriginT, OffsetT, ValueT > &lhs, OffsetPtr< OriginT, OffsetT, ValueT > &rhs)
interchanges two instances of the same type.
template<typename ValueT , typename LockableT , typename AllocatorT >
void swap (SharedPtr< ValueT, LockableT, AllocatorT > &lhs, SharedPtr< ValueT, LockableT, AllocatorT > &rhs)
interchanges two instances of the same type.
template<typename AllocatorT >
void swap (Any< AllocatorT > &lhs, Any< AllocatorT > &rhs)
interchanges two instances of same type.
template<size_t BitsSize>
void swap (Bitset< BitsSize > &lhs, Bitset< BitsSize > &rhs)
interchanges two instances of same type.
template<typename ValueT >
void swap (IntrusivePtr< ValueT > &lhs, IntrusivePtr< ValueT > &rhs)
interchanges two instances of the same type.
template<typename ValueT , size_t Capacity>
void swap (FixedVector< ValueT, Capacity > &lhs, FixedVector< ValueT, Capacity > &rhs)
interchanges the entities of two instances.
template<typename ValueT , typename AllocatorT >
void swap (Vector< ValueT, AllocatorT > &lhs, Vector< ValueT, AllocatorT > &rhs)
interchanges the entities of two instances.
template<typename CharT , typename AllocatorT >
void swap (String< CharT, AllocatorT > &lhs, String< CharT, AllocatorT > &rhs)
interchanges two instances of the same type.
Detailed Description
the root of all namespaces in hryky-codebase.
Function Documentation
template<typename T > T hryky::align_ceil (T value, alignment_type alignment)
rounds up an integer value to the nearest value aligned in bit.
Parameters
value is the value to be rounded up.
alignment is the number of alignment in bits.
Returns
rounded value
References align_floor().
Referenced by hryky::memory::heap::Arbitrary< OffsetT >::allocatable_size(), hryky::memory::heap::Arbitrary< OffsetT >::allocate(), hryky::memory::heap::Fixed::reset(), and hryky::memory::heap::Arbitrary< OffsetT >::reset().
template<typename T > T hryky::align_floor (T value, alignment_type alignment)
rounds down an integer value to the nearest value aligned in bit.
Parameters
value is the value to be rounded down.
alignment is the number of alignment in bits.
Returns
rounded value
Referenced by align_ceil(), and hryky::memory::heap::Arbitrary< OffsetT >::reset().
size_t hryky::hamming_weight (uint64_t const value)
counts the number of non-zero bit in 64 bits value.
See also
http://en.wikipedia.org/wiki/Hamming_weight
template<typename AllocatorT , typename Arg1T > AllocatorT::pointer hryky::instantiate (AllocatorT & allocator, Arg1T const & arg1)
allocates a memory and instantiates in the memory with one argument.
allocates a memory and instantiates in the memory by one argument.
References HRYKY_NULLPTR.
template<typename AllocatorT , typename Arg1T , typename Arg2T > AllocatorT::pointer hryky::instantiate (AllocatorT & allocator, Arg1T const & arg1, Arg2T const & arg2)
allocates a memory and instantiates in the memory with two arguments.
allocates a memory and instantiates in the memory by two arguments.
References HRYKY_NULLPTR.
template<typename T > bool hryky::is_aligned (T value, alignment_type alignment)
confirms whether an integer value is aligned in bit
Parameters
value is the value to be confirmed.
alignment is the number of alignment in bits.
Returns
aligned or not aligned
template<typename MainFuncT > int hryky::main (int argc, char const *const argv[], typename AsParameter< MainFuncT >::type func)
wrapper function to catch exception.
Parameters
argc is the first argument of entry point (almost always, main()).
argv is the second argument of entry point.
func is called in this function.
Return values
0 is success.
otherwise failure.
Attention
func must be able to be called as the function with two arguments, argc and argv.
func must return 0 if it completed successfully.
Examples:
test_main.cpp.
int hryky::main (int argc, char const *const argv[], main_func_pointer func) [inline]
wrapper function to catch exception.
Parameters
argc is the first argument of entry point (almost always, main()).
argv is the second argument of entry point.
func is called in this function.
Return values
0 is success.
otherwise failure.
template<typename InputIterator > void hryky::qsort (InputIterator const begin, InputIterator const end)
quick sort.
Parameters
begin specifies the beginning of the sorted range.
end specifies just after the last element in the sorted range.
Examples:
test_task_quicksort.cpp.
References hryky_log_debug, and hryky::qsort_internal::partition().
template<typename ValueT > hryky::reduction_type hryky::reduce (reduction::name_type const & name, ValueT value, typename EnableIf< IsEnum< ValueT > >::type * = HRYKY_NULLPTR)
creates a primitive object decomposed as int.
creates a primitive object decomposed as int.
Note
for conversion from enum to int.
hryky::reduction_type hryky::reduce (reduction::name_type const & name, char const *const & value)
creates a primitive object decomposed as string from a null-terminated character.
template<size_t Size> hryky::reduction_type hryky::reduce (reduction::name_type const & name, char const (&) src[Size])
creates a primitive object decomposed as string from an array of characters.
template<typename T > void hryky::release (T *& ptr)
release the instance that has release() method.
Parameters
ptr is the instance
ptr is the instance
If ptr is null-pointer, this function does nothing.
References HRYKY_NULLPTR.
template<typename Arg1T , typename Arg2T , typename Arg3T , typename Arg4T > hryky::Sequence4< Arg1T, Arg2T, Arg3T, Arg4T > hryky::sequence4 (Arg1T const & arg1, Arg2T const & arg2, Arg3T const & arg3, Arg4T const & arg4)
creates a sequence which has 4values.
creates a sequence which has 4 values.
template<typename DerivedT > void hryky::swap (DerivedT & src, DerivedT & src)
interchanges two instances of same type.
interchanges two instances of the same type. / interchanges two instances of the same type. void swap(Copyable & lhs, Copyable & rhs);
template<typename BaseT , typename ValueT > void hryky::swap (Adapter< BaseT, ValueT > & lhs, Adapter< BaseT, ValueT > & rhs)
interchanges two instances of same type.
interchanges two instances of the same type.
References hryky::Adapter< BaseT, ValueT >::swap().
Referenced by hryky::atomic::Accessor< ValueT, LockableT >::Accessor(), hryky::Adapter< BaseT, ValueT >::swap(), hryky::IntrusivePtr< ValueT >::swap(), and hryky::Vector< ValueT, AllocatorT >::swap().
template<typename BitsT > void hryky::swap (Bitfield< BitsT > & lhs, Bitfield< BitsT > & rhs)
interchanges two instances of same type.
interchanges two instances of the same type.
References hryky::Bitfield< BitsT >::swap().
template<typename IntT > void hryky::swap (Index< IntT > & lhs, Index< IntT > & rhs)
interchanges two instances of same type.
interchanges two instances of the same type.
References hryky::Index< IntT >::swap().
template<typename ResultT , size_t Size> void hryky::swap (NarrowToken< ResultT, Size > & lhs, NarrowToken< ResultT, Size > & rhs)
interchanges two instances of same type.
interchanges two instances of the same type.
References hryky::NarrowToken< ResultT, Size >::swap().
template<typename AllocatorT > void hryky::swap (Any< AllocatorT > & lhs, Any< AllocatorT > & rhs)
interchanges two instances of same type.
interchanges two instances of the same type.
References hryky::Any< AllocatorT >::swap().
template<size_t BitsSize> void hryky::swap (Bitset< BitsSize > & lhs, Bitset< BitsSize > & rhs)
interchanges two instances of same type.
interchanges two instances of the same type.
References hryky::Bitset< BitsSize >::swap().